apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ctf-wordpress
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        # Enable Secret Manager access
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
    spec:
      serviceAccountName: ctf-wordpress-sa  # Your service account
      containers:
      - image: gcr.io/YOUR_PROJECT_ID/ctf-wordpress:latest
        ports:
        - containerPort: 80
        env:
        - name: CTF_USE_SECRET_MANAGER
          value: "true"
        - name: CTF_GCP_PROJECT_ID
          value: "YOUR_PROJECT_ID"
        - name: WORDPRESS_DB_HOST
          value: "127.0.0.1:3306"
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: wordpress-db-name
              key: latest
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-db-user  
              key: latest
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-db-password
              key: latest
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
      # Cloud SQL Proxy sidecar
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.33.2
        command:
          - "/cloud_sql_proxy"
          - "-instances=YOUR_PROJECT_ID:YOUR_REGION:YOUR_INSTANCE_NAME=tcp:3306"
        securityContext:
          runAsNonRoot: true